#!/usr/bin/env bash

# Set appropriate month and date
if [ "$(date +%A)" = "Monday" ]; then
    month="$(date +%B)"
    day=$(date +%-d)
elif [ $(date +%u) -gt 5 ]; then
    month="$(date -d-monday +%B)"
    day=$(date -d-monday +%-d)
else
    month="$(date -dlast-monday +%B)"
    day=$(date -dlast-monday +%-d)
fi

menu_pdf="tmp/menu-${month}-${day}.pdf"

# get newest menu if not cached
if [ ! -f $menu_pdf ]; then
    if [ -f tmp/menu-* ]; then
        rm ./tmp/menu-*
    fi
    ./get_menu $menu_pdf && ./get_days $menu_pdf
fi


day=$(date +%A)
day_menu="tmp/${day,,}.txt"

if [ -f $day_menu ]; then
    echo ${day^^}
    cat $day_menu
else
    echo "${day^} menu is not available yet! Please check back in a little while."
fi
