#!/usr/bin/env bash

offset_x=220

monday_y=100
tuesday_y=230
wednesday_y=370
thursday_y=500
friday_y=630

width=400
height=130


declare -a days=( "monday" "tuesday" "wednesday" "thursday" "friday" )
declare -a day_offsets=( ${monday_y} ${tuesday_y} ${wednesday_y} ${thursday_y} ${friday_y} )

menu_pdf=$1
for i in "${!day_offsets[@]}"; do
    output="tmp/${days[$i]}.txt"
    pdftotext -x ${offset_x} -y ${day_offsets[$i]} -W ${width} -H ${height} -layout ${menu_pdf} ${output}
done
