#!/usr/bin/env bash

# GCafe menu url template
url="https://flikcafes.compass-usa.com/cafeG/DiningMenus/Menu%20{month}%20{day}.pdf"

# Set appropriate month and date
if [ "$(date +%A)" = "Monday" ]; then
    month="$(date +%B)"
    day=$(date +%-d)
elif [ $(date +%u) -gt 5 ]; then
    month="$(date -d-monday +%B)"
    day=$(date -d-monday +%-d)
else
    month="$(date -dlast-monday +%B)"
    day=$(date -dlast-monday +%-d)
fi

output="tmp/menu-${month}-${day}.pdf"
if [ $1 ]; then
    output=$1
fi

menu=$(echo "$url" | sed -E -e "s/\{month\}/${month}/g" -e "s/\{day\}/${day}/g")
curl -sf "$menu" -o "$output" || exit 1
